[lib]
name = "merger"
version = "0.1.0"

[package]
name = "merger"
version = "0.1.0"
authors = ["Sergey Borodin <bellispiritus@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"
filesize = "0.2.0"